device_path = '/dev/input/by-path/platform-i8042-serio-0-event-kbd'
abort_key = 'KeyPause'
exported_keys = ['KeyA', 'KeyB']

[layout]
KEY_A = 'KeyA'
KEY_B = 'KeyB'

[map]
KEY_A = 'map_to_key "KeyB"'
KEY_B = 'map_to_key "KeyA"'
